pipeline {
  agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
  stages {
    
          stage('Build') {
              sh 'mvn clean install'

          }

          stage('Image') {
              dir ('api-gateway') {
                  def app = docker.build "localhost:5000/api-gateway"
                  app.push()
              }
          }

          stage ('Run') {
              docker.image("localhost:5000/api-gateway").run('-p 2121:2121 -h api-gateway --name api-gateway --link discovery --link cryptocurrencies --link social-media-services')
          }

         

      }
}
